[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
AlgebraicMultigrid = "2169fc97-5a83-5252-b627-83903c6c433c"
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BracketingNonlinearSolve = "70df07ce-3d50-431d-a3e7-ca6ddb60ac1e"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
DocumenterInterLinks = "d12716ef-a0f6-4df4-a9f1-a5a34e75c656"
IncompleteLU = "40713840-3770-5561-ab4c-a76e7d0d7895"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LineSearch = "87fe0de2-c867-4266-b59a-2f0a94fc965b"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
NonlinearSolveBase = "be0214bd-f91f-a760-ac4e-3421ce2b2da0"
NonlinearSolveFirstOrder = "5959db7a-ea39-4486-b5fe-2dd0bf03d60d"
NonlinearSolveHomotopyContinuation = "2ac3b008-d579-4536-8c91-a1a5998c2f8b"
NonlinearSolveQuasiNewton = "9a2c21bd-3a47-402d-9113-8faf9a0ee114"
NonlinearSolveSciPy = "4827a3aa-8a82-4c61-8bd0-3c7d3e464ee5"
NonlinearSolveSpectralMethods = "26075421-4e9a-44e1-8bd1-420ed7ad02b2"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
PETSc = "ace2c81b-2b5f-4b1e-a30d-d662738edfe0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SciMLJacobianOperators = "19f34311-ddf3-4b8b-af20-060888a46c0e"
SimpleNonlinearSolve = "727e6d20-b764-4bd8-a329-72de5adea6c7"
SparseConnectivityTracer = "9f842d2f-2579-4b1d-911e-f412cf18a3f5"
SparseMatrixColorings = "0a514795-09f3-496d-8182-132a7b665d35"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SteadyStateDiffEq = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"

[sources.BracketingNonlinearSolve]
path = "../lib/BracketingNonlinearSolve"

[sources.NonlinearSolve]
path = ".."

[sources.NonlinearSolveBase]
path = "../lib/NonlinearSolveBase"

[sources.NonlinearSolveFirstOrder]
path = "../lib/NonlinearSolveFirstOrder"

[sources.NonlinearSolveHomotopyContinuation]
path = "../lib/NonlinearSolveHomotopyContinuation"

[sources.NonlinearSolveQuasiNewton]
path = "../lib/NonlinearSolveQuasiNewton"

[sources.NonlinearSolveSciPy]
path = "../lib/NonlinearSolveSciPy"

[sources.NonlinearSolveSpectralMethods]
path = "../lib/NonlinearSolveSpectralMethods"

[sources.SciMLJacobianOperators]
path = "../lib/SciMLJacobianOperators"

[sources.SimpleNonlinearSolve]
path = "../lib/SimpleNonlinearSolve"

[compat]
ADTypes = "1.9.0"
AlgebraicMultigrid = "0.5, 0.6, 1"
ArrayInterface = "6, 7"
BenchmarkTools = "1"
BracketingNonlinearSolve = "1"
DifferentiationInterface = "0.7.3"
Documenter = "1"
DocumenterCitations = "1"
DocumenterInterLinks = "1.0.0"
IncompleteLU = "0.2"
InteractiveUtils = "<0.0.1, 1"
LineSearch = "0.1"
LinearSolve = "2, 3"
NonlinearSolve = "4"
NonlinearSolveBase = "1.15, 2"
NonlinearSolveFirstOrder = "1"
NonlinearSolveHomotopyContinuation = "0.1"
NonlinearSolveQuasiNewton = "1"
NonlinearSolveSciPy = "1"
NonlinearSolveSpectralMethods = "1"
OrdinaryDiffEqTsit5 = "1.5"
PETSc = "0.3"
Plots = "1"
Random = "1.10"
SciMLBase = "2.116"
SciMLJacobianOperators = "0.1"
SimpleNonlinearSolve = "2"
SparseConnectivityTracer = "1"
SparseMatrixColorings = "0.4"
StaticArrays = "1"
SteadyStateDiffEq = "2"
Sundials = "4.11, 5"
